# You can define a fallback output for all modules that don't define their own.

[modules.LighthouseVIPER]
imports = ["Foundation", "UIKit", "RswiftResources"]
testableImports = ["LighthouseVIPER"]
sources = [
    "LighthouseVIPER/**/App/*Repository.swift",
    "LighthouseVIPER/**/Auth/*Repository.swift",
    "LighthouseVIPER/**/Auth/*Wrapper.swift",
    "LighthouseVIPER/**/Scenes/**/*Router.swift",
]

[modules.LighthouseVIPER.options]
protocolsOnly = true
keepDocumentation = false
omitHeaders = true
